spring.application.name=HolidayPlanners

spring.datasource.url=jdbc:postgresql://localhost:5432/HolidayPlanners
spring.datasource.username=postgres
spring.datasource.password=Ruth123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8084